#pragma once

#include "CoreMinimal.h"
#include "Styling/ISlateStyle.h"
#include "Styling/SlateStyle.h"

struct FButtonStyle;
struct FCheckBoxStyle;
struct FSlateBrush;

// ====================================================================================================================
// Shared Slate style set for the CK debugger suite's COMMON widgets.
//
// CkStyle:: (CkEditorTools) owns the color/typography tokens; this set owns the
// registered BRUSHES the common widgets need — texture-backed glow halos, the
// flat button used by underline tabs, and any brush that must outlive a paint
// call. Feature-debugger modules should reach for these before registering
// module-local equivalents.
//
// Glow brushes are monochrome white with an alpha falloff; tint them at the
// use site (SImage::ColorAndOpacity) with the tone color. Source PNGs live in
// Resources/Common/ and are regenerated by
// docs/plans/2026-07-18-goap-mission-control/generate_glow.ps1.
// ====================================================================================================================

class CKDEBUGGERCOMMON_API FCkDebuggerCommonStyle
{
public:
    static auto Initialize() -> void;
    static auto Shutdown() -> void;

    static auto Get() -> const ISlateStyle&;
    static auto GetStyleSetName() -> FName;

    // ----------------------------------------------------------------------------------------------------------------
    // Brush accessors are lifetime-safe: they return the style's missing brush
    // before initialization. (Icons are NOT here — they resolve through the
    // typed FCkIconStyle::Get_Brush in CkEditorTools.)
    // ----------------------------------------------------------------------------------------------------------------

    // Wide soft halo — card emphasis, active-chain leaf glow.
    static auto Get_GlowSoftBrush() -> const FSlateBrush*;

    // Crisp tight halo — chip trace-ring, small element glow.
    static auto Get_GlowTightBrush() -> const FSlateBrush*;

    // Transparent-normal flat button (hover = subtle bg) — underline tabs,
    // icon buttons, any "text that clicks" surface.
    static auto Get_FlatButtonStyle() -> const FButtonStyle&;

    // Suite-wide icon toggle surface used by debugger toolbars and contextual
    // boolean controls. Feature modules bind state; Common owns presentation.
    static auto Get_IconToggleStyle() -> const FCheckBoxStyle&;

private:
    static auto Create() -> TSharedRef<FSlateStyleSet>;

    static TSharedPtr<FSlateStyleSet> StyleInstance;
};

// ====================================================================================================================
